ALTER TABLE t_p80059633_maxogram_messenger.users 
ADD COLUMN IF NOT EXISTS avatar_url TEXT,
ADD COLUMN IF NOT EXISTS birth_date DATE,
ADD COLUMN IF NOT EXISTS username_last_changed TIMESTAMP DEFAULT CURRENT_TIMESTAMP;